version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: Model_Logger
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"

  api:
    build:
      context: ./api_service  # Path to your Dockerfile
    ports:
      - "8005:8005"  # Adjusted to match the app's port
    depends_on:
      - db
    environment:
      MYSQL_HOST: db  # Matches service name of the DB
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
      MYSQL_DATABASE: Model_Logger

