services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: Model_Logger
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql  # Mount the init_db.sql file

  api:
    build:
      context: ./api_service
    ports:
      - "8005:8005"
    depends_on:
      - db
    environment:
      MYSQL_HOST: db
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
      MYSQL_DATABASE: Model_Logger
